channels:
- conda-forge
- anaconda
dependencies:
- python=3.8.16
- pip:
  - adal==1.2.7
  - applicationinsights==0.11.10
  - arch==5.3.1
  - argcomplete==2.0.0
  - asttokens==2.2.1
  - attrs==22.2.0
  - azure-common==1.1.28
  - azure-core==1.26.3
  - azure-graphrbac==0.61.1
  - azure-identity==1.12.0
  - azure-mgmt-authorization==3.0.0
  - azure-mgmt-containerregistry==10.0.0
  - azure-mgmt-core==1.3.2
  - azure-mgmt-keyvault==10.1.0
  - azure-mgmt-resource==21.2.1
  - azure-mgmt-storage==20.1.0
  - azure-storage-blob==12.13.0
  - azure-storage-queue==12.5.0
  - azureml-automl-core==1.49.0
  - azureml-automl-runtime==1.49.0
  - azureml-core==1.49.0
  - azureml-dataprep==4.9.1
  - azureml-dataprep-native==38.0.0
  - azureml-dataprep-rslex==2.16.1
  - azureml-dataset-runtime==1.49.0
  - azureml-defaults==1.49.0
  - azureml-inference-server-http==0.8.0
  - azureml-interpret==1.49.0
  - azureml-mlflow==1.49.0
  - azureml-pipeline-core==1.49.0
  - azureml-responsibleai==1.49.0
  - azureml-telemetry==1.49.0
  - azureml-train-automl-client==1.49.0
  - azureml-train-automl-runtime==1.49.0
  - azureml-train-core==1.49.0
  - azureml-train-restclients-hyperdrive==1.49.0
  - azureml-training-tabular==1.49.0
  - backcall==0.2.0
  - backports-tempfile==1.0
  - backports-weakref==1.0.post1
  - bcrypt==4.0.1
  - bokeh==2.4.3
  - boto==2.49.0
  - cachetools==5.3.0
  - cmdstanpy==0.9.5
  - contextlib2==21.6.0
  - contourpy==1.0.7
  - cycler==0.11.0
  - cython==0.29.33
  - dask==2021.6.0
  - databricks-cli==0.17.4
  - dataclasses==0.6
  - debugpy==1.6.6
  - decorator==5.1.1
  - dice-ml==0.9
  - dill==0.3.6
  - distributed==2021.6.0
  - distro==1.8.0
  - docker==6.0.1
  - dotnetcore2==3.1.23
  - econml==0.14.0
  - entrypoints==0.4
  - ephem==4.1.4
  - erroranalysis==0.4.1
  - executing==1.2.0
  - fairlearn==0.8.0
  - fire==0.5.0
  - flask==2.2.3
  - flask-cors==3.0.10
  - flatbuffers==23.1.21
  - fonttools==4.38.0
  - fsspec==2023.1.0
  - gensim==3.8.3
  - gitdb==4.0.10
  - gitpython==3.1.31
  - google-api-core==2.11.0
  - google-auth==2.16.0
  - googleapis-common-protos==1.58.0
  - gunicorn==20.1.0
  - h5py==3.8.0
  - heapdict==1.0.1
  - humanfriendly==10.0
  - importlib-metadata==5.2.0
  - importlib-resources==5.10.2
  - inference-schema==1.5.1
  - interpret-community==0.28.0
  - interpret-core==0.2.7
  - ipykernel==6.6.0
  - ipython==8.10.0
  - isodate==0.6.1
  - itsdangerous==2.1.2
  - jedi==0.18.2
  - jeepney==0.8.0
  - jinja2==3.1.2
  - jsonpickle==2.2.0
  - jsonschema==4.17.3
  - jupyter-client==7.4.9
  - jupyter-core==5.2.0
  - keras2onnx==1.6.0
  - kiwisolver==1.4.4
  - knack==0.10.1
  - lightgbm==3.2.1
  - locket==1.0.0
  - lunarcalendar==0.0.9
  - markupsafe==2.0.1
  - matplotlib==3.7.0
  - matplotlib-inline==0.1.6
  - ml-wrappers==0.4.2
  - mlflow-skinny==2.1.1
  - mltable==1.1.0
  - msal==1.21.0
  - msal-extensions==1.0.0
  - msgpack==1.0.4
  - msrest==0.7.1
  - msrestazure==0.6.4
  - ndg-httpsclient==0.5.1
  - nest-asyncio==1.5.6
  - networkx==2.5
  - numba==0.55.2
  - oauthlib==3.2.2
  - onnx==1.12.0
  - onnxconverter-common==1.6.0
  - onnxmltools==1.4.1
  - onnxruntime==1.11.1
  - opencensus==0.11.1
  - opencensus-context==0.1.3
  - opencensus-ext-azure==1.1.8
  - packaging==21.3
  - paramiko==2.12.0
  - parso==0.8.3
  - partd==1.3.0
  - pathspec==0.11.0
  - patsy==0.5.3
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - pillow==9.4.0
  - pkginfo==1.9.6
  - pkgutil-resolve-name==1.3.10
  - platformdirs==3.0.0
  - pmdarima==1.7.1
  - portalocker==2.7.0
  - prompt-toolkit==3.0.36
  - property-cached==1.6.4
  - protobuf==3.20.1
  - ptyprocess==0.7.0
  - pure-eval==0.2.2
  - pyarrow==9.0.0
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pydantic==1.10.5
  - pygments==2.14.0
  - pyjwt==2.6.0
  - pynacl==1.5.0
  - pyparsing==3.0.9
  - pyrsistent==0.19.3
  - pyyaml==6.0
  - pyzmq==25.0.0
  - raiutils==0.3.0
  - requests-oauthlib==1.3.1
  - responsibleai==0.24.0
  - rsa==4.9
  - scipy==1.5.3
  - secretstorage==3.3.3
  - semver==2.13.0
  - skl2onnx==1.4.9
  - sklearn-pandas==1.7.0
  - slicer==0.0.7
  - smart-open==1.9.0
  - smmap==5.0.0
  - sortedcontainers==2.4.0
  - sparse==0.13.0
  - sqlparse==0.4.3
  - stack-data==0.6.2
  - statsmodels==0.11.1
  - tabulate==0.9.0
  - tblib==1.7.0
  - termcolor==2.2.0
  - toolz==0.12.0
  - tornado==6.2
  - tqdm==4.64.1
  - traitlets==5.9.0
  - typing-extensions==4.5.0
  - wcwidth==0.2.6
  - websocket-client==1.5.1
  - werkzeug==2.2.3
  - wrapt==1.12.1
  - zict==2.2.0
  - zipp==3.13.0
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- _py-xgboost-mutex=2.0
- appdirs=1.4.4
- boto3=1.15.18
- botocore=1.18.18
- brotlipy=0.7.0
- bzip2=1.0.8
- ca-certificates=2022.12.7
- certifi=2022.12.7
- cffi=1.15.1
- charset-normalizer=2.1.1
- cloudpickle=1.6.0
- convertdate=2.4.0
- cryptography=39.0.1
- fbprophet=0.7.1
- holidays=0.10.3
- idna=3.4
- jmespath=0.10.0
- joblib=0.14.1
- korean_lunar_calendar=0.3.1
- ld_impl_linux-64=2.40
- libblas=3.9.0
- libcblas=3.9.0
- libffi=3.4.2
- libgcc-ng=12.2.0
- libgfortran-ng=12.2.0
- libgfortran5=12.2.0
- libgomp=12.2.0
- liblapack=3.9.0
- libnsl=2.0.0
- libopenblas=0.3.21
- libsqlite=3.40.0
- libstdcxx-ng=12.2.0
- libuuid=2.32.1
- libxgboost=1.3.3
- libzlib=1.2.13
- llvmlite=0.38.1
- ncurses=6.3
- numpy=1.21.6
- openssl=3.0.8
- pandas=1.1.5
- pip=20.2.4
- pooch=1.6.0
- psutil=5.9.4
- py-cpuinfo=5.0.0
- py-xgboost=1.3.3
- pycparser=2.21
- pymeeus=0.5.12
- pyopenssl=23.0.0
- pysocks=1.7.1
- pystan=2.19.1.1
- python-dateutil=2.8.2
- python_abi=3.8
- pytz=2022.7.1
- readline=8.1.2
- requests=2.28.2
- s3transfer=0.3.7
- scikit-learn=0.22.1
- setuptools=59.8.0
- setuptools-git=1.2
- shap=0.39.0
- six=1.16.0
- tk=8.6.12
- urllib3=1.25.11
- wheel=0.38.4
- xz=5.2.6
name: project_environment
